name: temanbicara
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  chat_gpt_sdk: ^3.1.3
  cloud_firestore: ^5.6.0
  cupertino_icons: ^1.0.6
  curved_navigation_bar: ^1.0.6
  device_preview: ^1.2.0
  dropdown_search: ^6.0.1
  easy_date_timeline: ^2.0.9
  fancy_password_field: ^2.0.8
  firebase_core: ^3.9.0
  firebase_messaging: ^15.1.5
  fl_chart: ^0.71.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_chat_types: ^3.6.2
  flutter_chat_ui: ^1.6.15
  flutter_dotenv: ^5.2.1
  flutter_gemini: ^3.0.0
  flutter_launcher_icons: ^0.14.2
  flutter_local_notifications: ^18.0.1
  flutter_sliding_up_panel: ^2.1.1
  flutter_timer_countdown: ^1.0.7
  get: 4.6.6
  get_storage: ^2.1.1
  google_fonts: ^6.2.1
  google_generative_ai: ^0.4.6
  googleapis_auth: ^2.0.0
  http: ^1.2.2
  iconsax: ^0.0.8
  image_picker: ^1.1.2
  intl: 0.20.2
  lottie: ^3.1.3
  openai_dart: ^0.4.4
  path_provider: ^2.1.5
  pdf: ^3.11.3
  permission_handler: ^12.0.0+1
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.2.1
  syncfusion_flutter_gauges: ^29.1.38
  table_calendar: ^3.1.2
  timeline_tile: ^2.0.0
  uuid: ^4.5.1
  email_validator: ^3.0.0

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - "assets/images/"
    - "assets/icons/"
    - "assets/animations/"
    - "assets/data/"
    - "assets/firebase/"
    - .env

flutter_launcher_icons:
  android: true
  ios: true
  min_sdk_android: 21
  image_path: "assets/images/logo.png"
  adaptive_icon_foreground: "assets/images/logo_foreground.png"
  adaptive_icon_background: "#ffffff"
