name: temanbicara
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.6
  curved_navigation_bar: ^1.0.6
  device_preview: ^1.2.0
  flutter:
    sdk: flutter
  flutter_sliding_up_panel: ^2.1.1
  get: 4.6.6
  google_fonts: ^6.2.1
  iconsax: ^0.0.8

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - "assets/images/"
    - "assets/icons/"
