name: Continous Testing

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  test:
    name: Run Flutter Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.0'
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Setup dummy env & asset
        run: |
            mkdir -p assets/firebase
            mkdir -p assets/images
            echo "" > assets/images/logo.png
            echo "DUMMY=1" > .env
            echo "{}" > assets/firebase/service-account.json
    
      - name: Run analyzer (ignore asset warnings)
        run: |
            flutter analyze | tee analyze.log || true
            cat analyze.log
            if grep -q "error •" analyze.log; then
                echo "Found analyzer errors"
                exit 1
            else
                echo "Only warnings, safe to continue"
            fi

      - name: Run tests
        run: flutter test

