# =======================================================
# VERSI FINAL - 28 MEI 2025
# =======================================================
name: Build and Release APK

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-release:
    name: Build and Release APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      
      - name: Set up Flutter (Latest Stable)
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable' 
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Create Secret Files
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > android/app/temanbicara_key.keystore
          echo "${{ secrets.GOOGLE_SERVICES_JSON_BASE64 }}" | base64 --decode > android/app/google-services.json
          echo "${{ secrets.ENV_FILE_CONTENT }}" > .env
          mkdir -p assets/firebase
          echo "${{ secrets.SERVICE_ACCOUNT_JSON }}" > assets/firebase/service-account.json

      - name: Create key.properties file
        run: |
          echo "storeFile=temanbicara_key.keystore" > android/key.properties
          echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/key.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties

      - name: Build Signed APK
        run: flutter build apk --release

      # DIHAPUS: Langkah 'Find APK Location' sudah tidak perlu lagi.
      
      # PERBAIKAN DI SINI: Menggunakan path yang sudah terbukti benar dari hasil debug.
      - name: Rename APK
        run: mv build/app/outputs/apk/release/app-release.apk build/app/outputs/apk/release/teman-bicara-${{ github.ref_name }}.apk

      # PERBAIKAN DI SINI: Path file untuk diunggah juga disesuaikan.
      - name: Create GitHub Release and Upload APK
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ github.ref_name }}
          generate_release_notes: true
          files: build/app/outputs/apk/release/teman-bicara-${{ github.ref_name }}.apk